### ISSUE TITLE
Exclude KaOS-Community-Packages.github.io

### ISSUE THREAD

**Issue by ColinDuquesnoy** [bvaudour/kcp#10]
KaOS-Community-Packages.github.io (the new website for KCP) is listed in octopi. Installing it obviously leads to a "Package not found" message.

I'd suggest to add an ignore rule for this repository or check if the repo contains a PKGBUILD.

![screenshot_20160420_104736](https://cloud.githubusercontent.com/assets/1681217/14668632/830deb82-06e5-11e6-95cc-da3c52eeb689.png)

**Comment by bvaudour** [comment]
Thanks for your report. It's corrected with https://github.com/bvaudour/kcp/commit/14700afdaae80425000cb03619862fa7d88e7a92

**Comment by ColinDuquesnoy** [comment]
Thank you!
