### ISSUE TITLE
Another instance of kcp is running! messge - kcp keeps running after close when installation

### ISSUE THREAD

**Issue by grodrigo** [bvaudour/kcp#13]
When I choose a file to install a package with kcp on Octopi, if I enter on edition of the installation file (i.e "Do you want to edit sublime-text-dev.install? [y/N] n") and close Octopi without saving or quit edition properly, it keeps running.
When I try to run kcp again even from console or from Octopi I get the message "Another instance of kcp is running!" but I couldn't find that another instance, and Octopi doesn't resolve it properly.

It is the same when I say yes to "Do you want to edit PKGBUILD? [Y/n]" and close Octopi too. Even more, in this case it ask me root permissions to close it, and warn me about risk my system (Why? I didn't install nothing yet!), I chose to close the window without giving permissions, and voila it closed anyway and the result was the same, it keeps running somewhere.

In both cases the solution was to manually remove /tmp/kcp.lock

**Comment by bvaudour** [comment]
I added interrpution motives’ capture on https://github.com/bvaudour/kcp/commit/df13041eee702a9c403253cf1f180557476d40a3

It should correct the problem next time.

**Comment by bvaudour** [comment]
kcp 0.91.0 is up in the repo. Closing…
